### PR TITLE
Cleanup go version

### PR DESCRIPTION
**Pull request by ph**
This project doesn't seems to work on go 1.12, because of the usage of
`NewRequestWithContext`, I've taken the liberty to bump it to 1.15 and
added a `.go-version` file.

```
winterfell~/zat(main|✔) % go build
./main.go:382:15: undefined: http.NewRequestWithContext
```

### CODE REVIEW

File: .go-version [hunk 1]
```diff
@@ -0,0 +1 @@
+1.15.6
```
Comment (graphaelli) [inline .go-version:1]: What consumes this file?
